// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetBlockchain() {
  return window['go']['main']['App']['GetBlockchain']();
}

export function GetDecryptedMessage(arg1, arg2) {
  return window['go']['main']['App']['GetDecryptedMessage'](arg1, arg2);
}

export function GetMessages() {
  return window['go']['main']['App']['GetMessages']();
}

export function GetMessagesFromPeer(arg1) {
  return window['go']['main']['App']['GetMessagesFromPeer'](arg1);
}

export function GetPeerList() {
  return window['go']['main']['App']['GetPeerList']();
}

export function GetUserPeerID() {
  return window['go']['main']['App']['GetUserPeerID']();
}

export function SendEncryptedMessage(arg1, arg2) {
  return window['go']['main']['App']['SendEncryptedMessage'](arg1, arg2);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}
