// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function Greet(arg1:string):Promise<string>;

export function SendMessage(arg1:string):Promise<void>;

export function StartAppService(arg1:backend.AppService):Promise<void>;
