// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetBlockchain() {
  return window['go']['main']['App']['GetBlockchain']();
}

export function GetMessages() {
  return window['go']['main']['App']['GetMessages']();
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}
